### PR TITLE
Search busline and advanced search completed

### PR DESCRIPTION
**Pull request by knelasevero**
Signed-off-by: Lucas Seveo lucassalves65@gmail.com

### CODE REVIEW

**Comment by oparley** [comment]
Please, show the amount of buslines found in the advanced search :)

**Comment by oparley** [comment]
Check the error messages, there are some accents missing and some of the messages are in the wrong context or outdated.

**Comment by oparley** [comment]
Deactivate or hide buttons(links) that are not been used yet.

**Comment by oparley** [comment]
Fix these smells too, please :)
https://landscape.io/diff/165992

**Comment by MacSoares** [comment]
Normalize methods docstrings to save this new bad smells
https://landscape.io/diff/167932

**Comment by MacSoares** [comment]
Advanced search needs to be fixed. 
BUG: When using advanced search for a busline, if I pass only a value in 'terminal' field, the site shows me all the buslines, and not only the buslines for that terminal.

**Pull request merged**
